// Full House Hunters / 1Key Games Catalog from https://house-hunters.epusara.com/games/

const BASE_URL = 'https://house-hunters.epusara.com';

const RAW_GAMES = [
  { id: 184, slug: "10-minutes-till-dawn", title: "10 Minutes Till Dawn", logo: `${BASE_URL}/images/game-covers/10-minutes-till-dawn.webp`, file: `${BASE_URL}/games/cl10minutestildawn.html`, category: "action" },
  { id: 173, slug: "12-mini-battles", title: "12 Mini Battles", logo: `${BASE_URL}/images/game-covers/12-mini-battles.webp`, file: `${BASE_URL}/games/12%20Mini%20Battles.html`, category: "multiplayer" },
  { id: 205, slug: "2048", title: "2048", logo: `${BASE_URL}/images/game-covers/2048.png`, file: `${BASE_URL}/games/cl2048.html`, category: "puzzle" },
  { id: 74, slug: "1v1-lol", title: "1v1.lol", logo: `${BASE_URL}/images/game-covers/1v1-lol.webp`, file: `${BASE_URL}/games/1v1.LoL.html`, category: "shooter" },
  { id: 46, slug: "a-small-world-cup", title: "A Small World Cup", logo: `${BASE_URL}/images/asmallworldcup.png`, file: `${BASE_URL}/games/asmallworldcup.html`, category: "sports" },
  { id: 82, slug: "ages-of-conflict", title: "Ages of Conflict", logo: `${BASE_URL}/images/game-covers/ages-of-conflict.webp`, file: `${BASE_URL}/games/clagesofconflict.html`, category: "strategy" },
  { id: 106, slug: "amanda-the-adventurer", title: "Amanda the Adventurer", logo: `${BASE_URL}/images/game-covers/amanda-the-adventurer.webp`, file: `${BASE_URL}/games/Amanda%20the%20Adventurer.html`, category: "horror" },
  { id: 188, slug: "andys-apple-farm", title: "Andy's Apple Farm", logo: `${BASE_URL}/images/game-covers/andys-apple-farm.webp`, file: `${BASE_URL}/games/Andy's%20Apple%20Farm.html`, category: "horror" },
  { id: 43, slug: "angry-birds", title: "Angry Birds", logo: `${BASE_URL}/images/bird.webp`, file: `${BASE_URL}/games/angrybirds.html`, category: "classic" },
  { id: 83, slug: "awesome-tanks-2", title: "Awesome Tanks 2", logo: `${BASE_URL}/images/game-covers/awesome-tanks-2.webp`, file: `${BASE_URL}/games/Awesome%20Tanks%202.html`, category: "action" },
  { id: 226, slug: "baby-sniper-in-vietnam", title: "Baby Sniper In Vietnam", logo: `${BASE_URL}/images/game-covers/babysniper.webp`, file: `${BASE_URL}/games/Baby%20Sniper%20In%20Vietnam.html`, category: "shooter" },
  { id: 178, slug: "backrooms", title: "Backrooms", logo: `${BASE_URL}/images/game-covers/backrooms.webp`, file: `${BASE_URL}/games/clbackrooms.html`, category: "horror" },
  { id: 85, slug: "bacon-may-die", title: "Bacon May Die", logo: `${BASE_URL}/images/game-covers/bacon-may-die.webp`, file: `${BASE_URL}/games/Bacon%20May%20Die.html`, category: "action" },
  { id: 84, slug: "bad-parenting-1", title: "Bad Parenting 1", logo: `${BASE_URL}/images/game-covers/bad-parenting-1.webp`, file: `${BASE_URL}/games/clbadparenting.html`, category: "horror" },
  { id: 107, slug: "bad-time-simulator", title: "Bad Time Simulator", logo: `${BASE_URL}/images/game-covers/bad-time-simulator.webp`, file: `${BASE_URL}/games/Bad%20Time%20Simulator.html`, category: "arcade" },
  { id: 108, slug: "balatro", title: "Balatro", logo: `${BASE_URL}/images/game-covers/balatro.webp`, file: `${BASE_URL}/games/clbalatrogba.html`, category: "strategy" },
  { id: 86, slug: "bank-robbery-3", title: "Bank Robbery 3", logo: `${BASE_URL}/images/game-covers/bank-robbery-3.webp`, file: `${BASE_URL}/games/Bank%20Robbery%203.html`, category: "shooter" },
  { id: 120, slug: "baseball-bros", title: "Baseball Bros", logo: `${BASE_URL}/images/game-covers/baseball-bros.webp`, file: `${BASE_URL}/games/Baseball%20Bros.html`, category: "sports" },
  { id: 227, slug: "ben-10-omniverse", title: "Ben 10 Omniverse", logo: `${BASE_URL}/images/game-covers/ogom.jpg`, file: `${BASE_URL}/games/Ben%2010%20Omniverse.html`, category: "action" },
  { id: 228, slug: "ben-10-protector-of-earth", title: "Ben 10 Protector of Earth", logo: `${BASE_URL}/images/game-covers/protecotr.webp`, file: `${BASE_URL}/games/Ben%2010%20Protector%20of%20Earth.html`, category: "action" },
  { id: 6, slug: "basketball-random", title: "Basketball Random", logo: `${BASE_URL}/images/game-covers/basketball-random.png`, file: `${BASE_URL}/games/random.html`, category: "sports" },
  { id: 10, slug: "basketball-stars", title: "Basketball Stars", logo: `${BASE_URL}/images/game-covers/basketball-stars.png`, file: `${BASE_URL}/games/stars.html`, category: "sports" },
  { id: 87, slug: "bendy-and-the-ink-machine", title: "Bendy and the Ink Machine", logo: `${BASE_URL}/images/game-covers/bendy-and-the-ink-machine.webp`, file: `${BASE_URL}/games/Bendy%20and%20the%20Ink%20Machine.html`, category: "horror" },
  { id: 18, slug: "bot-life", title: "Bit Life", logo: `${BASE_URL}/images/game-covers/bot-life.png`, file: `${BASE_URL}/games/botlife.html`, category: "simulation" },
  { id: 206, slug: "bitplanes", title: "BitPlanes", logo: `${BASE_URL}/images/game-covers/bitplanes.png`, file: `${BASE_URL}/games/BitPlanes.html`, category: "arcade" },
  { id: 189, slug: "blade-ball", title: "Blade Ball", logo: `${BASE_URL}/images/game-covers/blade-ball.webp`, file: `${BASE_URL}/games/Blade%20Ball.html`, category: "action" },
  { id: 78, slug: "blackjack", title: "BlackJack", logo: `${BASE_URL}/images/game-covers/blackjack.webp`, file: `${BASE_URL}/games/BlackJack.html`, category: "card" },
  { id: 56, slug: "block-blast", title: "Block Blast", logo: `${BASE_URL}/images/game-covers/block-blast.webp`, file: `${BASE_URL}/games/blockblast.html`, category: "puzzle" },
  { id: 42, slug: "bloons-td-4", title: "Bloons TD 4", logo: `${BASE_URL}/images/game-covers/bloons-td-4.png`, file: `${BASE_URL}/games/bloonstd4.html`, category: "strategy" },
  { id: 207, slug: "bloodmoney", title: "BLOODMONEY!", logo: `${BASE_URL}/images/game-covers/bloodmoney.png`, file: `${BASE_URL}/games/BLOODMONEY!.html`, category: "action" },
  { id: 58, slug: "bloxorz", title: "Bloxorz", logo: `${BASE_URL}/images/game-covers/bloxorz.webp`, file: `${BASE_URL}/games/bloxorz.html`, category: "puzzle" },
  { id: 79, slug: "bob-the-robber-2", title: "Bob The Robber 2", logo: `${BASE_URL}/images/game-covers/bob-the-robber-2.webp`, file: `${BASE_URL}/games/Bob%20The%20Robber.html`, category: "action" },
  { id: 330, slug: "binding-of-isaac-wrath-of-the-lamb", title: "Binding of Isaac Wrath of The Lamb", logo: `${BASE_URL}/images/game-covers/bidningofissac.webp`, file: `${BASE_URL}/games/Binding%20of%20Isaac%20Wrath%20of%20The%20Lamb.html`, category: "action" },
  { id: 88, slug: "boxing-random", title: "Boxing Random", logo: `${BASE_URL}/images/game-covers/boxing-random.webp`, file: `${BASE_URL}/games/Boxing%20Random.html`, category: "sports" },
  { id: 89, slug: "bridge-race", title: "Bridge Race", logo: `${BASE_URL}/images/game-covers/bridge-race.avif`, file: `${BASE_URL}/games/Bridge%20Race.html`, category: "arcade" },
  { id: 229, slug: "brotato", title: "Brotato", logo: `${BASE_URL}/images/game-covers/brooo.png`, file: `${BASE_URL}/games/Brotato.html`, category: "action" },
  { id: 208, slug: "buildnow-gg", title: "BuildNow.gg", logo: `${BASE_URL}/images/game-covers/buildnow-gg.png`, file: `${BASE_URL}/games/BuildNow.gg.html`, category: "shooter" },
  { id: 24, slug: "buckshot-roulette", title: "Buckshot Roulette", logo: `${BASE_URL}/images/game-covers/buckshot-roulette.png`, file: `${BASE_URL}/games/buck.html`, category: "horror" },
  { id: 140, slug: "bust-a-loop", title: "Bust a Loop", logo: `${BASE_URL}/images/game-covers/bust-a-loop.webp`, file: `${BASE_URL}/games/Bust%20a%20Loop.html`, category: "arcade" },
  { id: 25, slug: "celeste", title: "Celeste", logo: `${BASE_URL}/images/game-covers/celeste.png`, file: `${BASE_URL}/games/cel.html`, category: "platformer" },
  { id: 246, slug: "cheese-rolling", title: "Cheese Rolling", logo: `${BASE_URL}/images/game-covers/cheese-rolling.png`, file: `${BASE_URL}/games/Cheese%20Rolling.html`, category: "arcade" },
  { id: 109, slug: "clash-of-vikings", title: "Clash Of Vikings", logo: `${BASE_URL}/images/game-covers/clash-of-vikings.webp`, file: `${BASE_URL}/games/Clash%20Of%20Vikings.html`, category: "strategy" },
  { id: 141, slug: "class-of-09", title: "Class of '09", logo: `${BASE_URL}/images/game-covers/class-of-09.webp`, file: `${BASE_URL}/games/Class%20of%20'09.html`, category: "story" },
  { id: 75, slug: "cluster-rush", title: "Cluster Rush", logo: `${BASE_URL}/images/game-covers/cluster-rush.webp`, file: `${BASE_URL}/games/Cluster%20Rush.html`, category: "action" },
  { id: 59, slug: "cookie-clicker", title: "Cookie Clicker", logo: `${BASE_URL}/images/game-covers/cookie-clicker.webp`, file: `${BASE_URL}/games/cookieclicker.html`, category: "clicker" },
  { id: 200, slug: "cloverpit", title: "Cloverpit", logo: `${BASE_URL}/images/game-covers/cloverpit.jpeg`, file: `${BASE_URL}/games/343434.html`, category: "arcade" },
  { id: 121, slug: "cooking-mama", title: "Cooking Mama", logo: `${BASE_URL}/images/game-covers/cooking-mama.webp`, file: `${BASE_URL}/games/Cooking%20Mama.html`, category: "casual" },
  { id: 32, slug: "core-ball", title: "Core Ball", logo: `${BASE_URL}/images/game-covers/core-ball.png`, file: `${BASE_URL}/games/core.html`, category: "arcade" },
  { id: 91, slug: "crazy-cattle-3d", title: "Crazy Cattle 3D", logo: `${BASE_URL}/images/game-covers/crazy-cattle-3d.webp`, file: `${BASE_URL}/games/cattle3d.html`, category: "arcade" },
  { id: 142, slug: "crazy-chicken-3d", title: "Crazy Chicken 3D", logo: `${BASE_URL}/images/game-covers/crazy-chicken-3d.webp`, file: `${BASE_URL}/games/Crazy%20Chicken%203D.html`, category: "arcade" },
  { id: 143, slug: "crazy-kitty-3d", title: "Crazy Kitty 3D", logo: `${BASE_URL}/images/game-covers/crazy-kitty-3d.webp`, file: `${BASE_URL}/games/Crazy%20Kitty%203D.html`, category: "arcade" },
  { id: 60, slug: "crossy-road", title: "Crossy Road", logo: `${BASE_URL}/images/game-covers/crossy-road.webp`, file: `${BASE_URL}/games/crossyroad.html`, category: "arcade" },
  { id: 209, slug: "csgo-clicker", title: "CSGO Clicker", logo: `${BASE_URL}/images/game-covers/csgo-clicker.webp`, file: `${BASE_URL}/games/clcsgoclicker.html`, category: "clicker" },
  { id: 61, slug: "cube-field", title: "Cube Field", logo: `${BASE_URL}/images/game-covers/cube-field.webp`, file: `${BASE_URL}/games/cubefield.html`, category: "arcade" },
  { id: 76, slug: "cuphead", title: "Cuphead", logo: `${BASE_URL}/images/game-covers/cuphead.webp`, file: `${BASE_URL}/games/Cuphead.html`, category: "action" },
  { id: 17, slug: "death-run-3d", title: "Death Run 3D", logo: `${BASE_URL}/images/game-covers/death-run-3d.png`, file: `${BASE_URL}/games/run.html`, category: "action" },
  { id: 247, slug: "dice-a-million", title: "Dice A Million", logo: `${BASE_URL}/images/game-covers/dice-a-million.png`, file: `${BASE_URL}/games/Dice%20A%20Million.html`, category: "casual" },
  { id: 122, slug: "deltarune", title: "Deltarune", logo: `${BASE_URL}/images/game-covers/deltarune.webp`, file: `${BASE_URL}/games/cldeltarune.html`, category: "rpg" },
  { id: 166, slug: "deltatraveler", title: "Deltatraveler", logo: `${BASE_URL}/images/game-covers/deltatraveler.webp`, file: `${BASE_URL}/games/cldeltatraveler.html`, category: "rpg" },
  { id: 144, slug: "destroy-the-car-3d", title: "Destroy The Car 3D", logo: `${BASE_URL}/images/game-covers/destroy-the-car-3d.webp`, file: `${BASE_URL}/games/Destroy%20The%20Car%203D.html`, category: "action" },
  { id: 145, slug: "doge-miner", title: "Doge Miner", logo: `${BASE_URL}/images/game-covers/doge-miner.webp`, file: `${BASE_URL}/games/Doge%20Miner.html`, category: "clicker" },
  { id: 195, slug: "dungeons-degenerate-gamblers", title: "Dungeons & Degenerate Gamblers", logo: `${BASE_URL}/images/game-covers/dungeons-degenerate-gamblers.jpeg`, file: `${BASE_URL}/games/Gamblers.html`, category: "strategy" },
  { id: 62, slug: "draw-joust", title: "Draw Joust", logo: `${BASE_URL}/images/game-covers/draw-joust.webp`, file: `${BASE_URL}/games/drawjoust.html`, category: "action" },
  { id: 33, slug: "drift-boss", title: "Drift Boss", logo: `${BASE_URL}/images/game-covers/drift-boss.png`, file: `${BASE_URL}/games/cldriftboss.html`, category: "racing" },
  { id: 22, slug: "drift-hunters", title: "Drift Hunters", logo: `${BASE_URL}/images/game-covers/drift-hunters.png`, file: `${BASE_URL}/games/drift.html`, category: "racing" },
  { id: 1, slug: "drive-mad", title: "Drive Mad", logo: `${BASE_URL}/images/game-covers/drive-mad.webp`, file: `${BASE_URL}/games/drivemad.html`, category: "racing" },
  { id: 146, slug: "elastic-man", title: "Elastic Man", logo: `${BASE_URL}/images/game-covers/elastic-man.webp`, file: `${BASE_URL}/games/Elastic%20Man.html`, category: "casual" },
  { id: 147, slug: "endoparasitic", title: "Endoparasitic", logo: `${BASE_URL}/images/game-covers/endoparasitic.webp`, file: `${BASE_URL}/games/Endoparasitic.html`, category: "horror" },
  { id: 93, slug: "escape-road-2", title: "Escape Road 2", logo: `${BASE_URL}/images/game-covers/escape-road-2.webp`, file: `${BASE_URL}/games/clescaperoad-2.html`, category: "racing" },
  { id: 248, slug: "escape-road-city-2", title: "Escape Road City 2", logo: `${BASE_URL}/images/game-covers/escape-road-city-2.png`, file: `${BASE_URL}/games/Escape%20Road%20City%202.html`, category: "racing" },
  { id: 249, slug: "escape-road-3", title: "Escape Road 3", logo: `${BASE_URL}/images/game-covers/escape-road-3.png`, file: `${BASE_URL}/games/Escape%20Road%203.html`, category: "racing" },
  { id: 110, slug: "evil-glitch", title: "Evil Glitch", logo: `${BASE_URL}/images/game-covers/evil-glitch.webp`, file: `${BASE_URL}/games/Evil%20Glitch.html`, category: "arcade" },
  { id: 111, slug: "fear-and-hunger", title: "Fear & Hunger", logo: `${BASE_URL}/images/game-covers/fear-and-hunger.webp`, file: `${BASE_URL}/games/Fear%20&%20Hunger.html`, category: "horror" },
  { id: 112, slug: "fears-to-fathom-home-alone", title: "Fears to Fathom: Home Alone", logo: `${BASE_URL}/images/game-covers/fears-to-fathom-home-alone.webp`, file: `${BASE_URL}/games/Fears%20to%20Fathom_%20Home%20Alone.html`, category: "horror" },
  { id: 133, slug: "five-nights-at-epsteins", title: "Five Nights at Epstein's", logo: `${BASE_URL}/images/game-covers/five-nights-at-epsteins.webp`, file: `${BASE_URL}/games/Five%20Nights%20at%20Epstein's.html`, category: "horror" },
  { id: 44, slug: "flappy-bird", title: "Flappy Bird", logo: `${BASE_URL}/images/flap.webp`, file: `${BASE_URL}/games/flappybird.html`, category: "arcade" },
  { id: 8, slug: "flight-simulator", title: "Flight Simulator", logo: `${BASE_URL}/images/game-covers/flight-simulator.png`, file: `${BASE_URL}/games/sim.html`, category: "simulation" },
  { id: 51, slug: "fnaf-1", title: "FNAF 1", logo: `${BASE_URL}/images/game-covers/fnaf-1.avif`, file: `${BASE_URL}/games/fnaf1.html`, category: "horror" },
  { id: 124, slug: "fnaf-2", title: "FNAF 2", logo: `${BASE_URL}/images/game-covers/fnaf-2.webp`, file: `${BASE_URL}/games/Five%20Nights%20at%20Freddy's%202.html`, category: "horror" },
  { id: 134, slug: "fnaf-3", title: "FNAF 3", logo: `${BASE_URL}/images/game-covers/fnaf-3.webp`, file: `${BASE_URL}/games/Five%20Nights%20at%20Freddy's%203.html`, category: "horror" },
  { id: 135, slug: "fnaf-4", title: "FNAF 4", logo: `${BASE_URL}/images/game-covers/fnaf-4.webp`, file: `${BASE_URL}/games/Five%20Nights%20at%20Freddy's%204.html`, category: "horror" },
  { id: 9, slug: "fnaf", title: "FNAF Sister Location", logo: `${BASE_URL}/images/game-covers/fnaf.webp`, file: `${BASE_URL}/games/fnaf.html`, category: "horror" },
  { id: 50, slug: "fnaf-ucn", title: "FNAF Ultimate Custom Night", logo: `${BASE_URL}/images/game-covers/fnaf-ucn.webp`, file: `${BASE_URL}/games/fnafucn.html`, category: "horror" },
  { id: 123, slug: "football-bros", title: "Football Bros", logo: `${BASE_URL}/images/game-covers/football-bros.webp`, file: `${BASE_URL}/games/Football%20Bros.html`, category: "sports" },
  { id: 148, slug: "fruit-ninja", title: "Fruit Ninja", logo: `${BASE_URL}/images/game-covers/fruit-ninja.webp`, file: `${BASE_URL}/games/clfruitninja.html`, category: "arcade" },
  { id: 136, slug: "funny-shooter-2", title: "Funny Shooter 2", logo: `${BASE_URL}/images/game-covers/funny-shooter-2.webp`, file: `${BASE_URL}/games/clfunnyshooter2.html`, category: "shooter" },
  { id: 5, slug: "geometry-dash", title: "Geometry Dash", logo: `${BASE_URL}/images/game-covers/geometry-dash.png`, file: `${BASE_URL}/games/dash.html`, category: "arcade" },
  { id: 180, slug: "geometry-dash-subzero", title: "Geometry Dash Subzero", logo: `${BASE_URL}/images/game-covers/geometry-dash-subzero.webp`, file: `${BASE_URL}/games/clgdsubzero.html`, category: "arcade" },
  { id: 63, slug: "get-yoked", title: "Get Yoked", logo: `${BASE_URL}/images/game-covers/get-yoked.webp`, file: `${BASE_URL}/games/getyoked.html`, category: "action" },
  { id: 64, slug: "getting-over-it", title: "Getting Over It", logo: `${BASE_URL}/images/game-covers/getting-over-it.webp`, file: `${BASE_URL}/games/gettingoverit.html`, category: "platformer" },
  { id: 65, slug: "gladihoppers", title: "Gladihoppers", logo: `${BASE_URL}/images/game-covers/gladihoppers.webp`, file: `${BASE_URL}/games/gladhoppers.html`, category: "action" },
  { id: 174, slug: "goblin-goopmaxxing", title: "Goblin Goopmaxxing", logo: `${BASE_URL}/images/game-covers/goblin-goopmaxxing.jpg`, file: `${BASE_URL}/games/Goblin%20Goopmaxxing.html`, category: "casual" },
  { id: 149, slug: "google-baseball", title: "Google Baseball", logo: `${BASE_URL}/images/game-covers/google-baseball.webp`, file: `${BASE_URL}/games/Google%20Baseball.html`, category: "sports" },
  { id: 167, slug: "google-dino", title: "Google Dino", logo: `${BASE_URL}/images/game-covers/google-dino.webp`, file: `${BASE_URL}/games/clgoogledino.html`, category: "classic" },
  { id: 194, slug: "gta-vice-city", title: "Grand Theft Auto: Vice City", logo: `${BASE_URL}/images/gta.png`, file: `${BASE_URL}/games/gta-vice-city.html`, category: "action" },
  { id: 113, slug: "gorilla-tag", title: "Gorilla Tag", logo: `${BASE_URL}/images/game-covers/gorilla-tag.webp`, file: `${BASE_URL}/games/Gorilla%20Tag.html`, category: "action" },
  { id: 12, slug: "granny", title: "Granny", logo: `${BASE_URL}/images/game-covers/granny.png`, file: `${BASE_URL}/games/granny.html`, category: "horror" },
  { id: 150, slug: "growden-io", title: "Growden.io", logo: `${BASE_URL}/images/game-covers/growden-io.webp`, file: `${BASE_URL}/games/Growden.io.html`, category: "multiplayer" },
  { id: 28, slug: "gun-spin", title: "Gun Spin", logo: `${BASE_URL}/images/game-covers/gun-spin.png`, file: `${BASE_URL}/games/spin.html`, category: "action" },
  { id: 94, slug: "half-life", title: "Half Life", logo: `${BASE_URL}/images/game-covers/half-life.webp`, file: `${BASE_URL}/games/Half%20Life.html`, category: "shooter" },
  { id: 80, slug: "happy-wheels", title: "Happy Wheels", logo: `${BASE_URL}/images/game-covers/happy-wheels.webp`, file: `${BASE_URL}/games/Happy%20Wheels.html`, category: "action" },
  { id: 95, slug: "highway-racer-2", title: "Highway Racer 2", logo: `${BASE_URL}/images/game-covers/highway-racer-2.webp`, file: `${BASE_URL}/games/clhighwayracer2.html`, category: "racing" },
  { id: 23, slug: "hollow-knight", title: "Hollow Knight", logo: `${BASE_URL}/images/game-covers/hollow-knight.png`, file: `${BASE_URL}/games/knight.html`, category: "action" },
  { id: 250, slug: "hollow-knight-silksong", title: "Hollow Knight: Silksong", logo: `${BASE_URL}/images/game-covers/hollow-knight-silksong.png`, file: `${BASE_URL}/games/Hollow%20Knight%20Silksong.html`, category: "action" },
  { id: 96, slug: "hotline-miami", title: "Hotline Miami", logo: `${BASE_URL}/images/game-covers/hotline-miami.webp`, file: `${BASE_URL}/games/Hotline%20Miami.html`, category: "action" },
  { id: 30, slug: "idle-breakout", title: "Idle Breakout", logo: `${BASE_URL}/images/game-covers/idle-breakout.png`, file: `${BASE_URL}/games/breakout.html`, category: "clicker" },
  { id: 21, slug: "idle-dice", title: "Idle Dice", logo: `${BASE_URL}/images/game-covers/idle-dice.png`, file: `${BASE_URL}/games/dice.html`, category: "clicker" },
  { id: 77, slug: "idle-mining-empire", title: "Idle Mining Empire", logo: `${BASE_URL}/images/game-covers/idle-mining-empire.webp`, file: `${BASE_URL}/games/Idle%20Mining%20Empire.html`, category: "clicker" },
  { id: 216, slug: "the-impossible-quiz", title: "The Impossible Quiz", logo: `${BASE_URL}/images/game-covers/qui.png`, file: `${BASE_URL}/games/The%20Impossible%20Quiz.html`, category: "puzzle" },
  { id: 114, slug: "iron-lung", title: "Iron Lung", logo: `${BASE_URL}/images/game-covers/iron-lung.webp`, file: `${BASE_URL}/games/Iron%20Lung.html`, category: "horror" },
  { id: 182, slug: "iron-snout", title: "Iron Snout", logo: `${BASE_URL}/images/game-covers/iron-snout.webp`, file: `${BASE_URL}/games/clironsnout.html`, category: "action" },
  { id: 97, slug: "jelly-drift", title: "Jelly Drift", logo: `${BASE_URL}/images/game-covers/jelly-drift.webp`, file: `${BASE_URL}/games/Jelly%20Drift.html`, category: "racing" },
  { id: 211, slug: "jelly-mario", title: "Jelly Mario", logo: `${BASE_URL}/images/game-covers/jelly-mario.png`, file: `${BASE_URL}/games/Jelly%20Mario.html`, category: "arcade" },
  { id: 151, slug: "johnny-trigger", title: "Johnny Trigger", logo: `${BASE_URL}/images/game-covers/johnny-trigger.webp`, file: `${BASE_URL}/games/Johnny%20Trigger.html`, category: "shooter" },
  { id: 175, slug: "karlson", title: "Karlson", logo: `${BASE_URL}/images/game-covers/karlson.webp`, file: `${BASE_URL}/games/Karlson.html`, category: "action" },
  { id: 125, slug: "kindergarten", title: "Kindergarten", logo: `${BASE_URL}/images/game-covers/kindergarten.webp`, file: `${BASE_URL}/games/Kindergarten.html`, category: "story" },
  { id: 212, slug: "kindergarten-2", title: "Kindergarten 2", logo: `${BASE_URL}/images/game-covers/kindergarten-2.png`, file: `${BASE_URL}/games/Kindergarten%202.html`, category: "story" },
  { id: 251, slug: "kindergarten-3", title: "Kindergarten 3", logo: `${BASE_URL}/images/game-covers/kindergarten-3.png`, file: `${BASE_URL}/games/Kindergarten%203.html`, category: "story" },
  { id: 57, slug: "legend-of-zelda-ocarina-of-time", title: "Legend of Zelda Ocarina of Time", logo: `${BASE_URL}/images/game-covers/legend-of-zelda-ocarina-of-time.webp`, file: `${BASE_URL}/games/zelda.html`, category: "rpg" },
  { id: 201, slug: "legend-of-zelda", title: "Legend Of Zelda", logo: `${BASE_URL}/images/game-covers/legend-of-zelda.webp`, file: `${BASE_URL}/games/clloz1.html`, category: "rpg" },
  { id: 202, slug: "legend-of-zelda-the-minish-cap", title: "Legend Of Zelda The Minish Cap", logo: `${BASE_URL}/images/game-covers/zelda-minish-cap.jpg`, file: `${BASE_URL}/games/cllozminishcap.html`, category: "rpg" },
  { id: 203, slug: "legend-of-zelda-the-spirit-tracks", title: "Legend Of Zelda The Spirit Tracks", logo: `${BASE_URL}/images/game-covers/legend-of-zelda-the-spirit-tracks.jpg`, file: `${BASE_URL}/games/cllozspirittracks.html`, category: "rpg" },
  { id: 204, slug: "legend-of-zelda-phantom-hourglass", title: "Legend Of Zelda Phantom Hourglass", logo: `${BASE_URL}/images/game-covers/legend-of-zelda-phantom-hourglass.jpg`, file: `${BASE_URL}/games/cllozphantomhourglass.html`, category: "rpg" },
  { id: 39, slug: "madalin-stunt-cars-3", title: "Madalin Stunt Cars 2", logo: `${BASE_URL}/images/game-covers/car.png`, file: `${BASE_URL}/games/clmadstuntcars2.html`, category: "racing" },
  { id: 54, slug: "masked-forces-unlimited", title: "Masked Forces Unlimited", logo: `${BASE_URL}/images/game-covers/masked-forces-unlimited.webp`, file: `${BASE_URL}/games/maskedforces.html`, category: "shooter" },
  { id: 66, slug: "melon-playground", title: "Melon Playground", logo: `${BASE_URL}/images/game-covers/melon-playground.webp`, file: `${BASE_URL}/games/melonplayground.html`, category: "sandbox" },
  { id: 11, slug: "minecraft", title: "Minecraft 1.12.2", logo: `${BASE_URL}/images/game-covers/minecraft.png`, file: `${BASE_URL}/games/craft.html`, category: "sandbox" },
  { id: 119, slug: "minecraft-1-8-8", title: "Minecraft 1.8.8", logo: `${BASE_URL}/images/game-covers/minecraft-1-8-8.png`, file: `${BASE_URL}/games/Minecraft%201.8.8.html`, category: "sandbox" },
  { id: 252, slug: "minecraft-pocket-edition", title: "Minecraft Pocket Edition", logo: `${BASE_URL}/images/game-covers/minecraft-pocket-edition.jpg`, file: `${BASE_URL}/games/Minecraft%20Pocket%20Edition.html`, category: "sandbox" },
  { id: 187, slug: "midnight-shift", title: "Midnight Shift", logo: `${BASE_URL}/images/game-covers/midnight-shift.webp`, file: `${BASE_URL}/games/midnight_shift.html`, category: "horror" },
  { id: 152, slug: "minesweeper-mania", title: "Minesweeper Mania", logo: `${BASE_URL}/images/game-covers/minesweeper-mania.webp`, file: `${BASE_URL}/games/Minesweeper%20Mania.html`, category: "puzzle" },
  { id: 15, slug: "monkey-mart", title: "Monkey Mart", logo: `${BASE_URL}/images/game-covers/monkey-mart.png`, file: `${BASE_URL}/games/mart.html`, category: "casual" },
  { id: 126, slug: "monster-tracks", title: "Monster Tracks", logo: `${BASE_URL}/images/game-covers/monster-tracks.webp`, file: `${BASE_URL}/games/Monster%20Tracks.html`, category: "racing" },
  { id: 153, slug: "moto-x3m-3", title: "Moto X3M 3", logo: `${BASE_URL}/images/game-covers/moto-x3m-3.webp`, file: `${BASE_URL}/games/Moto%20X3M%203.html`, category: "racing" },
  { id: 67, slug: "moto-x3m-spooky", title: "Moto X3M Spooky", logo: `${BASE_URL}/images/game-covers/moto-x3m-spooky.webp`, file: `${BASE_URL}/games/motox3mspooky.html`, category: "racing" },
  { id: 176, slug: "mountain-bike-runner", title: "Mountain Bike Runner", logo: `${BASE_URL}/images/game-covers/mountain-bike-runner.webp`, file: `${BASE_URL}/games/BIKER.html`, category: "racing" },
  { id: 190, slug: "my-friend-pedro", title: "My Friend Pedro", logo: `${BASE_URL}/images/game-covers/my-friend-pedro.webp`, file: `${BASE_URL}/games/clmyfriendpedro.html`, category: "action" },
  { id: 230, slug: "my-friend-pedro-arena", title: "My Friend Pedro Arena", logo: `${BASE_URL}/images/game-covers/arena.jpg`, file: `${BASE_URL}/games/My%20Friend%20Pedro%20Arena.html`, category: "action" },
  { id: 213, slug: "offroad-mountain-bike", title: "Offroad Mountain Bike", logo: `${BASE_URL}/images/game-covers/offroad-mountain-bike.png`, file: `${BASE_URL}/games/clmxoffroadmaster.html`, category: "sports" },
  { id: 127, slug: "ovo", title: "OvO", logo: `${BASE_URL}/images/game-covers/ovo.avif`, file: `${BASE_URL}/games/clovofixed.html`, category: "platformer" },
  { id: 98, slug: "papas-bakeria", title: "Papa's Bakeria", logo: `${BASE_URL}/images/game-covers/papas-bakeria.webp`, file: `${BASE_URL}/games/Papa's%20Bakeria.html`, category: "casual" },
  { id: 115, slug: "papas-cheeseria", title: "Papa's Cheeseria", logo: `${BASE_URL}/images/game-covers/papas-cheeseria.webp`, file: `${BASE_URL}/games/Papa's%20Cheeseria.html`, category: "casual" },
  { id: 116, slug: "papas-cupcakeria", title: "Papa's Cupcakeria", logo: `${BASE_URL}/images/game-covers/papas-cupcakeria.webp`, file: `${BASE_URL}/games/Papa's%20Cupcakeria.html`, category: "casual" },
  { id: 99, slug: "papas-sushiria", title: "Papa's Sushiria", logo: `${BASE_URL}/images/game-covers/papas-sushiria.jpeg`, file: `${BASE_URL}/games/Papa's%20Sushiria.html`, category: "casual" },
  { id: 68, slug: "paper-io-2", title: "Paper.io 2", logo: `${BASE_URL}/images/game-covers/paper-io-2.webp`, file: `${BASE_URL}/games/paperio2.html`, category: "multiplayer" },
  { id: 214, slug: "people-playground", title: "People Playground", logo: `${BASE_URL}/images/game-covers/people-playground.png`, file: `${BASE_URL}/games/People%20Playground.html`, category: "sandbox" },
  { id: 220, slug: "please-dont-touch-anything", title: "Please Dont Touch Anything", logo: `${BASE_URL}/images/game-covers/please-dont-touch-anything.jpg`, file: `${BASE_URL}/games/Please%20Dont%20Touch%20Anything.html`, category: "puzzle" },
  { id: 117, slug: "plants-vs-deads", title: "Plants vs Zombies", logo: `${BASE_URL}/images/game-covers/plants-vs-deads.webp`, file: `${BASE_URL}/games/Plants%20vs%20Zombies.html`, category: "strategy" },
  { id: 181, slug: "modded-plinko", title: "Plinko With Cheats", logo: `${BASE_URL}/images/game-covers/modded-plinko.webp`, file: `${BASE_URL}/plinko-game-online.github.io-main/build/`, category: "arcade" },
  { id: 29, slug: "plinko", title: "Plinko", logo: `${BASE_URL}/images/game-covers/plinko.webp`, file: `${BASE_URL}/games/plinko.html`, category: "arcade" },
  { id: 3, slug: "poly-track", title: "Poly Track", logo: `${BASE_URL}/images/game-covers/poly-track.png`, file: `${BASE_URL}/games/polytrack.html`, category: "racing" },
  { id: 197, slug: "postal", title: "Postal", logo: `${BASE_URL}/images/game-covers/postal.jpg`, file: `${BASE_URL}/games/clpostal.html`, category: "action" },
  { id: 118, slug: "repo", title: "R.E.P.O", logo: `${BASE_URL}/images/game-covers/repo.webp`, file: `${BASE_URL}/games/R.E.P.O.html`, category: "action" },
  { id: 14, slug: "ragdoll-archers", title: "Ragdoll Archers", logo: `${BASE_URL}/images/game-covers/ragdoll-archers.png`, file: `${BASE_URL}/games/arch.html`, category: "action" },
  { id: 69, slug: "ragdoll-hit", title: "Ragdoll Hit", logo: `${BASE_URL}/images/game-covers/ragdoll-hit.avif`, file: `${BASE_URL}/games/clragollhit.html`, category: "action" },
  { id: 164, slug: "re-run", title: "RE:RUN", logo: `${BASE_URL}/images/game-covers/re-run.webp`, file: `${BASE_URL}/games/RE_RUN.html`, category: "action" },
  { id: 81, slug: "recoil", title: "Recoil", logo: `${BASE_URL}/images/game-covers/recoil.webp`, file: `${BASE_URL}/games/Recoil.html`, category: "action" },
  { id: 170, slug: "resident-evil-3", title: "Resident Evil 3", logo: `${BASE_URL}/images/game-covers/resident-evil-3.avif`, file: `${BASE_URL}/games/clre3.html`, category: "horror" },
  { id: 191, slug: "rio-rex", title: "Rio Rex", logo: `${BASE_URL}/images/game-covers/rio-rex.webp`, file: `${BASE_URL}/games/Rio%20Rex.html`, category: "action" },
  { id: 13, slug: "old-bowl", title: "Retro Bowl", logo: `${BASE_URL}/images/game-covers/old-bowl.png`, file: `${BASE_URL}/games/old-bowl.html`, category: "sports" },
  { id: 36, slug: "old-bowl-college", title: "Retro Bowl College", logo: `${BASE_URL}/images/game-covers/old-bowl-college.png`, file: `${BASE_URL}/games/oldbowlcollege.html`, category: "sports" },
  { id: 70, slug: "rogue-sergeant-the-final-operation", title: "Rogue Sergeant", logo: `${BASE_URL}/images/game-covers/rogue-sergeant-the-final-operation.webp`, file: `${BASE_URL}/games/roguesergeantthefinaloperation.html`, category: "action" },
  { id: 155, slug: "rolly-vortex", title: "Rolly Vortex", logo: `${BASE_URL}/images/game-covers/rolly-vortex.webp`, file: `${BASE_URL}/games/Rolly%20Vortex.html`, category: "arcade" },
  { id: 231, slug: "roulette-hero", title: "Roulette Hero", logo: `${BASE_URL}/images/game-covers/hero.png`, file: `${BASE_URL}/games/Roulette%20Hero.html`, category: "casual" },
  { id: 41, slug: "rooftop-snipers", title: "Rooftop Snipers", logo: `${BASE_URL}/images/game-covers/rooftop-snipers.png`, file: `${BASE_URL}/games/rooftop.html`, category: "shooter" },
  { id: 55, slug: "run-3", title: "Run 3", logo: `${BASE_URL}/images/game-covers/run-3.webp`, file: `${BASE_URL}/games/run3.html`, category: "arcade" },
  { id: 40, slug: "schoolboy-runaway", title: "SchoolBoy Runaway", logo: `${BASE_URL}/images/game-covers/schoolboy-runaway.png`, file: `${BASE_URL}/games/schoolboy.html`, category: "horror" },
  { id: 156, slug: "scrap-metal-3", title: "Scrap Metal 3", logo: `${BASE_URL}/images/game-covers/scrap-metal-3.webp`, file: `${BASE_URL}/games/Scrap%20Metal%203.html`, category: "racing" },
  { id: 185, slug: "side-effects", title: "Side Effects", logo: `${BASE_URL}/images/game-covers/side-effects.webp`, file: `${BASE_URL}/games/clsideeffects.html`, category: "horror" },
  { id: 100, slug: "slime-rancher", title: "Slime Rancher", logo: `${BASE_URL}/images/game-covers/slime-rancher.webp`, file: `${BASE_URL}/games/Slime%20Rancher.html`, category: "sandbox" },
  { id: 222, slug: "slender", title: "Slender", logo: `${BASE_URL}/images/game-covers/slender.jpg`, file: `${BASE_URL}/games/Slender.html`, category: "horror" },
  { id: 223, slug: "slendy-tubbies", title: "Slendy Tubbies", logo: `${BASE_URL}/images/game-covers/slendy-tubbies.webp`, file: `${BASE_URL}/games/clslendytubbies.html`, category: "horror" },
  { id: 2, slug: "slope", title: "Slope", logo: `${BASE_URL}/images/game-covers/slope.png`, file: `${BASE_URL}/games/slope.html`, category: "arcade" },
  { id: 71, slug: "slow-roads", title: "Slow Roads", logo: `${BASE_URL}/images/game-covers/slow-roads.webp`, file: `${BASE_URL}/games/slowroads.html`, category: "racing" },
  { id: 7, slug: "snow-rider-3d", title: "Snow Rider 3D", logo: `${BASE_URL}/images/game-covers/snow-rider-3d.png`, file: `${BASE_URL}/games/3d.html`, category: "arcade" },
  { id: 128, slug: "soccer-random", title: "Soccer Random", logo: `${BASE_URL}/images/game-covers/soccer-random.webp`, file: `${BASE_URL}/games/clsoccerrandomgood.html`, category: "sports" },
  { id: 31, slug: "solar-smash", title: "Solar Smash", logo: `${BASE_URL}/images/game-covers/solar-smash.png`, file: `${BASE_URL}/games/clsolarsmash.html`, category: "simulation" },
  { id: 129, slug: "soundboard", title: "Soundboard", logo: `${BASE_URL}/images/game-covers/soundboard.webp`, file: `${BASE_URL}/games/Soundboard.html`, category: "casual" },
  { id: 192, slug: "stackball-io", title: "Stackball io", logo: `${BASE_URL}/images/game-covers/stackball-io.webp`, file: `${BASE_URL}/games/clstackballio.html`, category: "arcade" },
  { id: 183, slug: "stake-mines", title: "Stake Mines", logo: `${BASE_URL}/images/game-covers/stake-mines.webp`, file: `${BASE_URL}/mines/stake_mines.html`, category: "arcade" },
  { id: 101, slug: "space-waves", title: "Space Waves", logo: `${BASE_URL}/images/game-covers/space-waves.webp`, file: `${BASE_URL}/games/Space%20Waves.html`, category: "arcade" },
  { id: 102, slug: "spacebar-clicker", title: "Spacebar Clicker", logo: `${BASE_URL}/images/game-covers/spacebar-clicker.webp`, file: `${BASE_URL}/games/spacebarclicker-single.html`, category: "clicker" },
  { id: 130, slug: "stickman-hook", title: "Stickman Hook", logo: `${BASE_URL}/images/game-covers/stickman-hook.webp`, file: `${BASE_URL}/games/Stickman%20Hook.html`, category: "arcade" },
  { id: 4, slug: "subway-surfers", title: "Subway Surfers", logo: `${BASE_URL}/images/game-covers/subway-surfers.png`, file: `${BASE_URL}/games/subwaysurfers.html`, category: "arcade" },
  { id: 193, slug: "suika-game", title: "Suika Game", logo: `${BASE_URL}/images/game-covers/suika-game.webp`, file: `${BASE_URL}/games/clsuika.html`, category: "puzzle" },
  { id: 158, slug: "superhot", title: "Superhot", logo: `${BASE_URL}/images/game-covers/superhot.webp`, file: `${BASE_URL}/games/clsuperhot.html`, category: "shooter" },
  { id: 16, slug: "survival-race-arena", title: "Survival Race Arena", logo: `${BASE_URL}/images/game-covers/survival-race-arena.png`, file: `${BASE_URL}/games/are.html`, category: "action" },
  { id: 159, slug: "survivor-io", title: "Survivor.io", logo: `${BASE_URL}/images/game-covers/survivor-io.webp`, file: `${BASE_URL}/games/Survivor.io.html`, category: "action" },
  { id: 160, slug: "tanuki-sunset", title: "Tanuki Sunset", logo: `${BASE_URL}/images/game-covers/tanuki-sunset.webp`, file: `${BASE_URL}/games/cltanukisunset.html`, category: "casual" },
  { id: 131, slug: "temple-run-2", title: "Temple Run 2", logo: `${BASE_URL}/images/game-covers/temple-run-2.avif`, file: `${BASE_URL}/games/Temple%20Run%202.html`, category: "arcade" },
  { id: 27, slug: "terraria", title: "Terraria", logo: `${BASE_URL}/images/game-covers/terraria.png`, file: `${BASE_URL}/games/t.html`, category: "sandbox" },
  { id: 26, slug: "thats-not-my-neighbor", title: "That's Not My Neighbor", logo: `${BASE_URL}/images/game-covers/thats-not-my-neighbor.png`, file: `${BASE_URL}/games/tat.html`, category: "horror" },
  { id: 215, slug: "they-are-coming", title: "They Are Coming", logo: `${BASE_URL}/images/game-covers/they-are-coming.png`, file: `${BASE_URL}/games/They%20Are%20Coming.html`, category: "action" },
  { id: 161, slug: "the-worlds-hardest-game", title: "The World's Hardest Game", logo: `${BASE_URL}/images/game-covers/hardestgame3.png`, file: `${BASE_URL}/games/The%20World's%20Hardest%20Game.html`, category: "puzzle" },
  { id: 199, slug: "the-man-from-the-window", title: "The Man From The Window", logo: `${BASE_URL}/images/game-covers/the-man-from-the-window.webp`, file: `${BASE_URL}/games/clthemaninthewindow.html`, category: "horror" },
  { id: 19, slug: "time-shooter", title: "Time Shooter", logo: `${BASE_URL}/images/game-covers/time-shooter.png`, file: `${BASE_URL}/games/time.html`, category: "shooter" },
  { id: 172, slug: "time-shooter-3-swat", title: "Time Shooter 3: SWAT", logo: `${BASE_URL}/images/game-covers/time-shooter-3-swat.webp`, file: `${BASE_URL}/games/Time%20Shooter%203_%20SWAT.html`, category: "shooter" },
  { id: 132, slug: "tiny-fishing", title: "Tiny Fishing", logo: `${BASE_URL}/images/game-covers/tiny-fishing.webp`, file: `${BASE_URL}/games/Tiny%20Fishing.html`, category: "casual" },
  { id: 47, slug: "tomb-of-the-mask", title: "Tomb Of The Mask", logo: `${BASE_URL}/images/tombofthemask.png`, file: `${BASE_URL}/games/tombofthemask.html`, category: "arcade" },
  { id: 162, slug: "traffic-racer", title: "Traffic Racer", logo: `${BASE_URL}/images/game-covers/traffic-racer.webp`, file: `${BASE_URL}/games/Traffic%20Racer.html`, category: "racing" },
  { id: 224, slug: "war-the-knights", title: "War The Knights", logo: `${BASE_URL}/images/game-covers/war-the-knights.png`, file: `${BASE_URL}/games/clwartheknight.html`, category: "action" },
  { id: 52, slug: "ultrakill", title: "ULTRAKILL", logo: `${BASE_URL}/images/game-covers/ultrakill.webp`, file: `${BASE_URL}/games/ultrakill.html`, category: "shooter" },
  { id: 103, slug: "undertale-yellow", title: "Undertale Yellow", logo: `${BASE_URL}/images/game-covers/undertale-yellow.webp`, file: `${BASE_URL}/games/Undertale%20Yellow.html`, category: "rpg" },
  { id: 73, slug: "vex-8", title: "Vex 8", logo: `${BASE_URL}/images/game-covers/vex-8.webp`, file: `${BASE_URL}/games/vex8.html`, category: "platformer" },
  { id: 104, slug: "webfishing", title: "WebFishing", logo: `${BASE_URL}/images/game-covers/webfishing.avif`, file: `${BASE_URL}/games/WebFishing.html`, category: "casual" },
  { id: 139, slug: "webgl-fluid", title: "WebGl Fluid", logo: `${BASE_URL}/images/game-covers/webgl-fluid.webp`, file: `${BASE_URL}/games/fluid.html`, category: "casual" },
  { id: 171, slug: "wordle", title: "Wordle", logo: `${BASE_URL}/images/game-covers/wordle.webp`, file: `${BASE_URL}/games/clwordle.html`, category: "puzzle" },
  { id: 163, slug: "yandere-simulator", title: "Yandere Simulator", logo: `${BASE_URL}/images/game-covers/yandere-simulator.webp`, file: `${BASE_URL}/games/Yandere%20Simulator.html`, category: "action" },
  { id: 105, slug: "you-vs-100-skibidi", title: "You vs. 100 Skibidi", logo: `${BASE_URL}/images/game-covers/you-vs-100-skibidi.webp`, file: `${BASE_URL}/games/clyouvs100skibidi.html`, category: "action" },
  { id: 232, slug: "agar-io-lite", title: "Agar.io Lite", logo: `${BASE_URL}/images/game-covers/agarlite.jpg`, file: `${BASE_URL}/games/Agar.io%20Lite.html`, category: "multiplayer" },
  { id: 233, slug: "among-us", title: "Among Us", logo: `${BASE_URL}/images/game-covers/amongus.jpg`, file: `${BASE_URL}/games/Among%20Us.html`, category: "multiplayer" },
  { id: 234, slug: "aqua-park", title: "Aqua Park", logo: `${BASE_URL}/images/game-covers/aquapark.png`, file: `${BASE_URL}/games/Aqua%20Park.html`, category: "arcade" },
  { id: 235, slug: "babel-tower", title: "Babel Tower", logo: `${BASE_URL}/images/game-covers/babeltower.png`, file: `${BASE_URL}/games/Babel%20Tower.html`, category: "strategy" },
  { id: 236, slug: "saul-goodman-run", title: "Saul Goodman Run", logo: `${BASE_URL}/images/game-covers/saulgoodam.png`, file: `${BASE_URL}/games/Saul%20Goodman%20Run.html`, category: "arcade" },
  { id: 237, slug: "fused-240", title: "Fused 240", logo: `${BASE_URL}/images/game-covers/fused240-cover.png`, file: `${BASE_URL}/games/Fused%20240.html`, category: "puzzle" },
  { id: 238, slug: "christmas-massacre", title: "Christmas Massacre", logo: `${BASE_URL}/images/game-covers/christmas-massacre-cover.png`, file: `${BASE_URL}/games/Christmas%20Massacre.html`, category: "horror" },
  { id: 239, slug: "cell-machine", title: "Cell Machine", logo: `${BASE_URL}/images/game-covers/cell-machine-cover.png`, file: `${BASE_URL}/games/Cell%20Machine.html`, category: "puzzle" },
  { id: 240, slug: "bart-blast", title: "Bart Blast", logo: `${BASE_URL}/images/game-covers/bart-blast-cover.png`, file: `${BASE_URL}/games/Bart%20Blast.html`, category: "action" },
  { id: 241, slug: "shred-sauce", title: "Shred Sauce", logo: `${BASE_URL}/images/game-covers/shred-sauce-cover.png`, file: `${BASE_URL}/games/Shred%20Sauce.html`, category: "sports" },
  { id: 242, slug: "skibidi-backrooms", title: "Skibidi Backrooms", logo: `${BASE_URL}/images/game-covers/ndonutrapem.webp`, file: `${BASE_URL}/games/Skibidi%20Backrooms.html`, category: "horror" },
  { id: 243, slug: "code-editor", title: "Code Editor", logo: `${BASE_URL}/images/game-covers/codeeditor.png`, file: `${BASE_URL}/games/Code%20Editor.html`, category: "utility" },
  { id: 244, slug: "omori", title: "Omori", logo: `${BASE_URL}/images/game-covers/omori.png`, file: `${BASE_URL}/games/Omori.html`, category: "rpg" },
  { id: 245, slug: "tung-tung-horror", title: "Tung Tung Horror", logo: `${BASE_URL}/images/game-covers/tungtung.jpeg`, file: `${BASE_URL}/games/tung.html`, category: "horror" }
];

export const HOUSE_HUNTERS_GAMES = RAW_GAMES.map(game => ({
  ...game,
  file: `/api/games/play?file=${encodeURIComponent(game.file)}`,
  logo: `/api/games/cover?url=${encodeURIComponent(game.logo)}`,
  rawFile: game.file,
  rawLogo: game.logo
}));
